# Generated by Django 4.2.2 on 2023-07-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('sign', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='currency_exchange.currencies')),
                ('target_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency', to='currency_exchange.currencies')),
            ],
        ),
    ]
