# Generated by Django 4.2.2 on 2023-07-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0002_alter_currencies_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencies',
            old_name='full_name',
            new_name='name',
        ),
    ]
