# Generated by Django 4.2.2 on 2023-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0003_rename_full_name_currencies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='sign',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
