# Generated by Django 4.2.2 on 2023-07-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0004_alter_currencies_code_alter_currencies_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='sign',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerates',
            unique_together={('base_currency_id', 'target_currency_id')},
        ),
    ]
